import asyncio
import json
from typing import Dict, List

import websockets
from fastapi import FastAPI
from aiortc import (
    RTCPeerConnection,
    RTCSessionDescription,
    MediaStreamTrack,
)
from aiortc.contrib.media import MediaRelay
from helpers.utils import add_ice_candidate_safe
from video_transform_track import VideoTransformTrack
from config import SIGNALING_URI, WAIT_FOR_TRACK_SECONDS, RECONNECT_DELAY_SECONDS

app = FastAPI()


# Global state
pcs: Dict[str, RTCPeerConnection] = {}  # clientId -> PeerConnection
pending_ice: Dict[str, List[dict]] = {}  # clientId -> list of pending ICE candidates
# Maps clientId -> asyncio.Future used to wait for first remote track
track_waiters: Dict[str, asyncio.Future] = {}




async def send_ice_candidate(ws, client_id: str, candidate_dict):
    """Send ICE candidate to Spring WebSocket."""
    try:
        out = {"type": "ice", "to": client_id, "candidate": candidate_dict}
        await ws.send(json.dumps(out))
        print(f"[{client_id}] 📤 ICE candidate sent: {candidate_dict}")
    except Exception as e:
        print(f"[{client_id}] ❌ Failed to send ICE candidate: {e}")


async def handle_offer(ws, msg):
    """
    Handle incoming 'offer' message forwarded by Spring.
    Expect msg to include 'from' (clientId) and 'sdp' (object or string).
    """
    client_id = msg.get("from")
    if not client_id:
        print("offer without 'from' -> ignoring")
        return

    # Clean up existing pc for client if present
    if client_id in pcs:
        try:
            await pcs[client_id].close()
        except Exception:
            pass
        pcs.pop(client_id, None)
        track_waiters.pop(client_id, None)

    pc = RTCPeerConnection()
    pcs[client_id] = pc

    # Future to wait for first remote track (so we can add relay-subscription as local track)
    loop = asyncio.get_running_loop()
    waiter: asyncio.Future = loop.create_future()
    track_waiters[client_id] = waiter

    @pc.on("icecandidate")
    def on_icecandidate(candidate):  # ✅ sync function
        """Handle local ICE candidates generated by aiortc."""
        print(f"[{client_id}] 🧊 Local ICE candidate generated: {candidate}")

        if candidate is None:
            # End of candidates
            print(f"[{client_id}] 🏁 ICE gathering complete")
            asyncio.create_task(send_ice_candidate(ws, client_id, None))
        else:
            # Send candidate to Spring
            candidate_dict = {
                "candidate": str(candidate),
                "sdpMid": candidate.sdpMid,
                "sdpMLineIndex": candidate.sdpMLineIndex,
            }
            asyncio.create_task(send_ice_candidate(ws, client_id, candidate_dict))

    @pc.on("track")
    def on_track(track: MediaStreamTrack):
        # fulfill waiter with the first remote track
        print(f"[{client_id}] remote track received: kind={track.kind}")
        w = track_waiters.get(client_id)
        if w and not w.done():
            w.set_result(track)
        # optional: spawn background task to read frames
        # asyncio.create_task(read_frames(client_id, track))


    # parse sdp
    sdp_obj = msg.get("sdp")
    if isinstance(sdp_obj, dict):
        sdp_type = sdp_obj.get("type", "offer")
        sdp_text = sdp_obj.get("sdp")
    else:
        sdp_type = msg.get("type", "offer")
        sdp_text = sdp_obj

    offer = RTCSessionDescription(sdp=sdp_text, type=sdp_type)
    await pc.setRemoteDescription(offer)

    # Wait for incoming track a short time so we can echo it back
    track = None
    try:
        track = await asyncio.wait_for(waiter, timeout=WAIT_FOR_TRACK_SECONDS)
    except asyncio.TimeoutError:
        # no remote track arrived in time -> proceed without echo
        print(
            f"[{client_id}] timeout waiting for remote track, will answer without echo"
        )

    if track:
        try:
            # here can make manipulation on the track
            processed_track = VideoTransformTrack(track)
            pc.addTrack(processed_track)
            
            # used when no modification is needed            
            # relay = MediaRelay()
            # relayed = relay.subscribe(track)
            # pc.addTrack(relayed)
            print(f"[{client_id}] added relayed local track (echo)")
        except Exception as e:
            print(f"[{client_id}] error adding relayed track: {e}")
            # traceback.print_exc()

    # Flush any pending ICE candidates
    pending = pending_ice.pop(client_id, [])
    for cand_dict in pending:
        try:
            await add_ice_candidate_safe(pc, client_id, cand_dict)
        except Exception as e:
            print(f"[{client_id}] addIceCandidate (pending) failed: {e}")

    # create and send answer
    answer = await pc.createAnswer()
    await pc.setLocalDescription(answer)

    out = {
        "type": "answer",
        "to": client_id,
        "sdp": {"type": pc.localDescription.type, "sdp": pc.localDescription.sdp},
    }
    await ws.send(json.dumps(out))
    print(f"[{client_id}] answer sent")



async def handle_ice(msg):
    """Handle incoming ICE candidate from JS client."""
    client_id = msg.get("from")
    cand_dict = msg.get("candidate")

    if not client_id:
        print("❌ ICE message without 'from', ignoring")
        return

    if not cand_dict:
        print(f"[{client_id}] 🏁 Received end-of-candidates signal")
        return

    # print(f"[{client_id}] 🧊 Received ICE candidate: {cand_dict}")

    pc = pcs.get(client_id)
    if not pc:
        print(f"[{client_id}] ❌ No peer connection found, buffering candidate")
        pending_ice.setdefault(client_id, []).append(cand_dict)
        return

    if pc.remoteDescription and pc.remoteDescription.type:
        await add_ice_candidate_safe(pc, client_id, cand_dict)
    else:
        print(f"[{client_id}] 📦 Buffering ICE candidate (no remote description)")
        pending_ice.setdefault(client_id, []).append(cand_dict)



async def handle_close(msg):
    """
    Handle close request from Spring.
    Expect msg: { "type": "close", "from": "<clientId>" }
    """
    client_id = msg.get("from")
    if not client_id:
        return

    pc = pcs.pop(client_id, None)
    if pc:
        # stop wszystkie VideoTransformTrack, jeśli są
        for sender in pc.getSenders():
            track = sender.track
            if isinstance(track, VideoTransformTrack):
                try:
                    await track.stop()  # <- zatrzymuje executor i taski
                except Exception as e:
                    print(f"[{client_id}] error stopping track: {e}")
        try:
            await pc.close()
        except Exception as e:
            print(f"[{client_id}] error closing pc: {e}")
            
    pending_ice.pop(client_id, None)
    track_waiters.pop(client_id, None)
    print(f"[{client_id}] cleaned up")


async def signaling_client_loop():
    """
    Connect to Spring WebSocket and respond to messages forwarded from JS clients.
    Reconnects on error with a delay.
    """
    while True:
        try:
            async with websockets.connect(SIGNALING_URI) as ws:
                print("Connected to signaling:", SIGNALING_URI)
                async for message in ws:
                    try:
                        msg = json.loads(message)
                    except Exception:
                        print("Received non-JSON message:", message)
                        continue

                    mtype = msg.get("type")

                    if mtype == "offer":
                        await handle_offer(ws, msg)
                    elif mtype == "ice":
                        await handle_ice(msg)
                    elif mtype == "close":
                        await handle_close(msg)
                    else:
                        print("Unknown message type:", mtype, "payload:", msg)
        except Exception as e:
            print("Signaling connection error:", e)
            print("Reconnecting in", RECONNECT_DELAY_SECONDS, "s...")
            await asyncio.sleep(RECONNECT_DELAY_SECONDS)


@app.on_event("startup")
async def startup_event():
    asyncio.create_task(signaling_client_loop())


@app.get("/")
async def check_status():
    return "Working"


@app.post("/generateFromText")
async def generate_from_text(payload: dict):
    return "To do"
