services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: docker/dev.Dockerfile

    # Set environment variables directly in the compose file
    # environment:
      # ENV_VARIABLE: ${ENV_VARIABLE}
      # NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    
    environment:
      WATCHPACK_POLLING: true

    init: true
    # Set environment variables based on the .env file
    env_file:
      - .env
      - .env.dev.local
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
      - /app/.next
    restart: always
    ports:
      - 3000:3000
    networks:
      - frontend

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  frontend:
  backend:
    # external: true // for now not needed
