services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: docker/prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always

    init: true
    ports:
      - 3000:3000
    networks:
      - frontend

  # Add more containers below (nginx, postgres, etc.)

volumes:
  pgdata:
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  frontend:
  backend:
    # external: true
